config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  get 'pages/home'

  get 'reports/index_download'

  resources :reports do
    member do
      get 'download'
      get 'update_positions'
    end
  end

  resources :portfolios
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flexws.rb
#!/usr/bin/env ruby

require 'faraday'
require 'nokogiri'
require 'logger'

class Flexws
  
  attr_accessor :logs

  def initialize
    @logs = Array.new
  end

  def fetch(token, reportid)
    response = Faraday.get "https://gdcdyn.interactivebrokers.com/Universal/servlet/FlexStatementService.SendRequest?t=#{token}&q=#{reportid}&v=3"

    xml_rsp = Nokogiri::XML(response.body)

    status = xml_rsp.xpath("/FlexStatementResponse/Status").text
    referenceCode = xml_rsp.xpath("/FlexStatementResponse/ReferenceCode").text
    url = xml_rsp.xpath("/FlexStatementResponse/Url").text
    
    @logs.push "#{response.body}"
    @logs.push "Parsing : status=#{status} referenceCode=#{referenceCode} url=#{url}"

    if status == "Success"
      finalrsp = Faraday.get "#{url}?q=#{referenceCode}&t=#{token}&v=3"
      return finalrsp.body
    else
      raise "Error while fetching IB"
    end
  end

 

  def toYahooFormat(portfolioid)
    result = Array.new
    result.push("Symbol,Current Price,Date,Time,Change,Open,High,Low,Volume,Trade Date,Purchase Price,Quantity,Commission,High Limit,Low Limit,Comment")

    Position.where(:portfolio_id => portfolioid).each do |p|
      result.push("#{p.ticker},,,,,,,,,,#{p.cost},#{p.quantity},,,,")
    end  
    
    return result.join("\n")
  end



  def fetchAndUpdateDB(token, positionid, portfolioid)
    str = fetch(token,positionid)
    @logs.push str

    Position.where(:portfolio_id => portfolioid).destroy_all

    str.each_line do |line|
      line.strip!
      if not line.empty?
        t = line.scan(/[a-zA-Z0-9.]+/)
        ticker = t[0]
        quantity = t[2]
        cost = t[3].to_f/t[2].to_f
        
        position = Position.new

        position.ticker = ticker
        position.quantity = quantity
        position.cost = cost
        position.portfolio_id = portfolioid
        position.save

      end
    end
  end

  


end

# rails console
# fws = Flexws.new
# fws.fetchAndSave("76141108763380332628992", "127673", 1)


#begin
#  fws = Flexws.new
#  puts fws.fetchAndParse("76141108763380332628992", "127673")
#  puts fws.fetchAndConvertPositions("76141108763380332628992", "127673")
#rescue => e
#  puts e.message
#  puts fws.logs
#end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
has_many :reports
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :portfolio
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :portfolio
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:name, :token)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, only: [:new, :create]
  
  protected

  def one_user_registered?
    if User.count == 1
      if user_signed_in?
        redirect_to root_path
      else
        redirect_to new_user_session_path
      end
    end  
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]


  def index_download
    @reports = Report.all
    @portfolios = Portfolio.all
  end


  def update_positions
    begin
      r = Report.find(params[:id])

      report_id = r.code
      token = r.portfolio.token
      portfolio_id = r.portfolio.id

      @fws = Flexws.new
      @fws.fetchAndUpdateDB(token, report_id, portfolio_id)

    rescue => e
      puts e.message
      puts @fws.logs
    end
  end


  def download
    r = Report.find(params[:id])

    name = "#{r.portfolio.name}_#{r.name}.csv"
    portfolio_id = r.portfolio.id
    
    @fws = Flexws.new
    str = @fws.toYahooFormat(portfolio_id)

    send_data str, filename: name, type: "application/csv"
  end



  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :code, :portfolio_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ibmanage" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ibmanage" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>             
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div class="sidebar-nav">
  <div class="well" style="width:300px; padding: 8px 0;">
    <ul class="nav nav-list"> 
      <li class="nav-header"> >>> </li>        

      <li><%= link_to 'Portfolios', portfolios_path %></li>
      <li><%= link_to 'Reports', reports_path %></li>
      <li><%= link_to 'Download', reports_index_download_path %></li>

    </ul>
  </div>
</div>

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name , :class => "col-md-4 control-label" %>
    <%= form.text_field :name , :class => "form-control input-md" %>
  </div>

  <div class="form-group">
    <%= form.label :token , :class => "col-md-4 control-label" %>
    <%= form.text_field :token , :class => "form-control input-md" %>
  </div>

  <div class="action">
    <%= form.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h4><%= File.expand_path(__FILE__) %></h4>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <legend>Edit portfolio</legend>
    </div>
  </div>

<%= render 'form', portfolio: @portfolio %> 

<br>
<%= link_to 'Back' , portfolios_path,  :class => "btn btn-info", :role => "button" %>

</div>

app/views/portfolios/index.html.erb
<h4><%= File.expand_path(__FILE__) %></h4>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <legend>List portfolio</legend>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-7">
      <table class="table table-responsive table-hover table-bordered ">
	<thead>
	  <tr class="info">
            <th>Name</th>
            <th>Token</th>
            <th colspan=2>Actions</th>
	  </tr>
	</thead>

	<tbody>
	  <% @portfolios.each do |portfolio| %>
	  <tr>
	    <td><%= portfolio.name %></td>
	    <td><%= portfolio.token %></td>
	    <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
	    <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  </tr>
	  <% end %>
	</tbody>

      </table>
    </div>
  </div>

<%= link_to 'New Portfolio', new_portfolio_path, :class => "btn btn-info", :role => "button" %>
<%= link_to 'Back' , root_path,  :class => "btn btn-info", :role => "button" %>

</div>

app/views/portfolios/new.html.erb
<h4><%= File.expand_path(__FILE__) %></h4>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <legend>New portfolio</legend>
    </div>
  </div>

<%= render 'form', portfolio: @portfolio %>

<br>
<%= link_to 'Back' , portfolios_path,  :class => "btn btn-info", :role => "button" %>

</div>

app/views/portfolios/show.html.erb
<h4><%= File.expand_path(__FILE__) %></h4>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <legend>Show portfolio</legend>
    </div>
  </div>

<p><label class="col-md-4">Name:</label> <%= @portfolio.name %></p>
<p><label class="col-md-4">Token:</label> <%= @portfolio.token %></p>


  <br>
  <%= link_to 'Edit', edit_portfolio_path(@portfolio) ,  :class => "btn btn-info", :role => "button" %>
  <%= link_to 'Back' , portfolios_path,  :class => "btn btn-info", :role => "button" %>

</div>

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= form.label :name , :class => "col-md-4 control-label" %>
    <%= form.text_field :name , :class => "form-control input-md" %>
  </div>

  <div class="form-group">
    <%= form.label :code , :class => "col-md-4 control-label" %>
    <%= form.text_field :code , :class => "form-control input-md" %>
  </div>

  <div class="form-group">
    <%= form.label :portfolio_id, :class => "col-md-4 control-label" %>
    <%= form.collection_select :portfolio_id, Portfolio.all, :id, :name, {}, { :class => "form-control input-md" } %>
  </div>


  <div class="action">
    <%= form.submit class: 'btn btn-info' %>
  </div>

<% end %>

app/views/reports/download.html.erb
<h4><%= File.expand_path(__FILE__) %></h4>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <legend>Download logs</legend>
    </div>
  </div>


<pre>
<%= @fws.logs.join("\n") %>
</pre>


<br>

<p><%= link_to 'Back' , reports_index_download_path, :class => "btn btn-info", :role => "button" %></p>




</div>

app/views/reports/edit.html.erb
<h4><%= File.expand_path(__FILE__) %></h4>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <legend>Edit report</legend>
    </div>
  </div>


<%= render 'form', report: @report %>

<br>
<%= link_to 'Back', reports_path,  :class => "btn btn-info", :role => "button" %>

app/views/reports/index.html.erb
<h4><%= File.expand_path(__FILE__) %></h4>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <legend>List reports</legend>
    </div>
  </div>

  <div class="row">
    <div class="col-md-7">
      <table class="table table-responsive table-hover table-bordered ">
        <thead>
          <tr class="info">
            <th>Name</th>
            <th>Code</th>
	    <th>Portfolio</th>
            <th colspan=2>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @reports.each do |report| %>
          <tr>
            <td><%= report.name %></td>
            <td><%= report.code %></td>
	    <td><%= report.portfolio.name %></td>
            <td><%= link_to 'Edit', edit_report_path(report) %></td>
            <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>

<%= link_to 'New Report', new_report_path, :class => "btn btn-info", :role => "button" %>
<%= link_to 'Back' , root_path,  :class => "btn btn-info", :role => "button" %>
</div>

app/views/reports/index_download.html.erb
<h4><%= File.expand_path(__FILE__) %></h4>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <legend>Positions</legend>
    </div>
  </div>

  <div class="row">
    <div class="col-md-7">

      <table class="table table-responsive table-hover table-bordered">
	<thead>
	  <tr class="info">
	    <th>Name</th>
	    <th>Code</th>
	    <th>Portfolio</th>
	    <th colspan="3"></th>
	  </tr>
	</thead>

	<tbody>
	  <% @reports.each do |report| %>
	  <tr>
            <td><%= report.name %></td>
            <td><%= report.code %></td>
            <td><%= report.portfolio.name %></td>
	    <td><%= link_to 'Update', update_positions_report_path(report) %></td>
	    <td><%= link_to 'Download', download_report_path(report) %></td>
	  </tr>
	  <% end %>
	</tbody>
      </table>

    </div>
  </div>


  <div>
    <legend>P123 import</legend>
    <% @portfolios.each do |portfolio| %>
  
    <p><b><%= portfolio.name %></b></p>
    <pre>
      <% Position.where(:portfolio_id => portfolio.id).each do |p| %> 
<%= "#{p.created_at.strftime('%m/%d/%Y')}\t#{p.ticker}\tBUY\t#{p.quantity}\t#{p.cost}\t0" %>
      <% end %>
    </pre>  

    <% end %>
  </div>



  <%= link_to 'Back' , root_path,  :class => "btn btn-info", :role => "button" %>
</div>

app/views/reports/new.html.erb
<h4><%= File.expand_path(__FILE__) %></h4>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <legend>New report</legend>
    </div>
  </div>

<%= render 'form', report: @report %>

<br>
<%= link_to 'Back' , reports_path,  :class => "btn btn-info", :role => "button" %>

</div>

app/views/reports/show.html.erb
<h4><%= File.expand_path(__FILE__) %></h4>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <legend>Show report</legend>
    </div>
  </div>

  <p><label class="col-md-4">Name:</label> <%= @report.name %></p>
  <p><label class="col-md-4">Code:</label> <%= @report.code %></p>
  <p><label class="col-md-4">Portfolio:</label> <%= @report.portfolio.name %></p>


  <br>
  <%= link_to 'Edit', edit_report_path(@report) ,  :class => "btn btn-info", :role => "button" %>
  <%= link_to 'Back' , reports_path,  :class => "btn btn-info", :role => "button" %>

</div>

app/views/reports/update_positions.html.erb
<h4><%= File.expand_path(__FILE__) %></h4>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <legend>Update logs</legend>
    </div>
  </div>


<pre>
<%= @fws.logs.join("\n") %>
</pre>


<br>

<p><%= link_to 'Back' , reports_index_download_path, :class => "btn btn-info", :role => "button" %></p>




</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>